language: java
sudo: false # for faster builds
jdk: oraclejdk8
script: 
  - mvn clean verify
  - mvn cobertura:cobertura
  
before_script:
  # For GUI testing
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

# Upload cobertura-maven code coverage report to codecov.io after building
after_success:
  - bash <(curl -s https://codecov.io/bash) -t db881e87-c34f-4d71-ac17-73575d05284e
